from .exceptions import custom_exceptions

exceptions = custom_exceptions
